### PR TITLE
add volume control for background music and button through all pages

### LINKED ISSUE #8: Adding volume control for background and sound effects
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

Add volume control slider so user can increase/decrease/turn off background music and sound effects

- [ ] some kind of slider to control volume
- [ ] should track user's setting across pages so it remains consistent

**ETA: give a rough time estimate to complete this issue** 1-2 days

**Additional Information?**

### PR DESCRIPTION
**Pull request by Kenry3**

### CODE REVIEW

**Comment by Barak-Horowitz** [comment]
fix formatting issues before merging

**Comment by Barak-Horowitz** [comment]
also change from using fixed pixel amount for size of assets in css documents to percentages to ensure this doesn't break on other browser sizes (ipad's, smaller computers, mobile...)

**Comment by mary7hu** [comment]
I'm thinking of pushing the merge off a little bit since we want to do a setting panel and we need to put the volume control in there. I think we already have a branch for setting panel, maybe we can merge it to that branch?

**Comment by Barak-Horowitz** [comment]
> I'm thinking of pushing the merge off a little bit since we want to do a setting panel and we need to put the volume control in there. I think we already have a branch for setting panel, maybe we can merge it to that branch?

sounds good to me

**Comment by mary7hu** [comment]
putting this inside setting panel

**Pull request closed without merging**
